name: Deploy compiled Node app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm run build

      # Create a clean production folder
      - name: Prepare production package
        run: |
          mkdir production
          cp -r dist production/
          cp package.json production/
          cp package-lock.json production/
          cd production
          npm ci --omit=dev

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2507780B9EAA4100B36DC4E7C53EA4C8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4A08B58510C402D9547BA7F1EF9E2D1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4FEB260AE5484A11886ABDEAD76578C9 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: plateops
          package: production